notifications.connector.name=pagerduty
notifications.connector.supported-connector-headers=${notifications.connector.name}
mp.messaging.incoming.incomingmessages.group.id=notifications-connector-pagerduty

quarkus.http.port=9009

# Configure the limit of how many messages the connector can process in parallel
smallrye.messaging.worker.connector-thread-pool.max-concurrency=20

quarkus.log.cloudwatch.enabled=false
quarkus.log.cloudwatch.level=INFO
quarkus.log.cloudwatch.log-stream-name=${HOST_NAME:notifications-connector-pagerduty}

quarkus.log.sentry.enabled=false
quarkus.log.sentry.in-app-packages=com.redhat.cloud.notifications

quarkus.kafka.devservices.port=9092

mp.messaging.tocamel.topic=platform.notifications.tocamel
mp.messaging.fromcamel.topic=platform.notifications.fromcamel

%test.quarkus.log.category."com.redhat.cloud.notifications".level=DEBUG

quarkus.rest-client.connector-rest-client.url=https://events.pagerduty.com/v2/enqueue
quarkus.rest-client.connector-rest-client.connect-timeout=5000
quarkus.rest-client.connector-rest-client.read-timeout=30000

quarkus.rest-client.sources.read-timeout=2000
quarkus.rest-client.sources.url=${clowder.endpoints.sources-api-svc.url:http://localhost:8000}
quarkus.rest-client.sources.trust-store=${clowder.endpoints.sources-api-svc.trust-store-path}
quarkus.rest-client.sources.trust-store-password=${clowder.endpoints.sources-api-svc.trust-store-password}
quarkus.rest-client.sources.trust-store-type=${clowder.endpoints.sources-api-svc.trust-store-type}

quarkus.rest-client.sources-oidc.read-timeout=2000
quarkus.rest-client.sources-oidc.url=${clowder.endpoints.sources-api-svc.url:http://localhost:8000}
quarkus.rest-client.sources-oidc.trust-store=${clowder.endpoints.sources-api-svc.trust-store-path}
quarkus.rest-client.sources-oidc.trust-store-password=${clowder.endpoints.sources-api-svc.trust-store-password}
quarkus.rest-client.sources-oidc.trust-store-type=${clowder.endpoints.sources-api-svc.trust-store-type}

# OIDC client configuration
quarkus.oidc-client.auth-server-url=REPLACE_ME_FROM_ENV_VAR
quarkus.oidc-client.client-id=REPLACE_ME_FROM_ENV_VAR
quarkus.oidc-client.credentials.secret=REPLACE_ME_FROM_ENV_VAR
quarkus.oidc-client.grant.type=client

quarkus.unleash.active=false
quarkus.unleash.url=http://localhost:4242
