#!/usr/bin/env bash
# When the admin-console build succeeds, place the compiled assets into the
# backend's META-INF directory and open a PR with the changes.
#
# Commits are GPG-signed using the key configured by the workflow's
# "Configure GPG signing" step.  The corresponding public key must be
# registered on a GitHub account so that commits appear as "Verified".

set -e

if [ -z "$(git config user.name)" ] || [ -z "$(git config user.email)" ]; then
  echo "Error: git user.name and user.email must be configured before running this script"
  exit 1
fi

TARGET="backend/src/main/resources/META-INF/resources/internal"

# Replace the previous build output with the fresh one.
rm -rf "${TARGET}"
mkdir -p "${TARGET}"
cp -r admin-console/src/main/webapp/build/* "${TARGET}"

# Stage the new content so we can detect whether anything actually changed.
# The `-f` flag is needed because the target directory is in .gitignore.
git add -f "${TARGET}"
if git diff --cached --quiet; then
  echo "No changes to commit, skipping PR creation"
  exit 0
fi

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="admin-console-update-${TIMESTAMP}"

git checkout -b "${BRANCH_NAME}"
git commit -S -m "Update admin-console build artifacts

Automatically generated by admin-console build workflow.
Triggered by: @${GITHUB_ACTOR}"

git push origin "${BRANCH_NAME}"

gh pr create \
  --title "Update admin-console build artifacts" \
  --base master \
  --head "${BRANCH_NAME}" \
  --body "This PR was automatically generated to update the admin-console build artifacts.

**Details:**
- Built from commit: \`${GITHUB_SHA}\`
- Triggered by: @${GITHUB_ACTOR}
- Branch: \`${BRANCH_NAME}\`

Please review and merge to update the admin console on master."
