#!/usr/bin/env bash
# When the build succeeds, we need to place the results in the backend META-INF code and commit it.
# Delete whatever is there and add the new build.

set -e

TARGET="backend/src/main/resources/META-INF/resources/internal"

rm -rf "${TARGET}"
mkdir -p "${TARGET}"
cp -r admin-console/src/main/webapp/build/* "${TARGET}"

# Configure git with GITHUB_ACTOR's identity
git config user.name "${GITHUB_ACTOR}"
git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

# Check if there are any changes
git add -f "${TARGET}"
if git diff --cached --quiet; then
  echo "No changes to commit, skipping PR creation"
  exit 0
fi

# Create a unique branch name with timestamp
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="admin-console-update-${TIMESTAMP}"

# Create and checkout new branch from current branch
git checkout -b "${BRANCH_NAME}"

# Commit changes with GITHUB_ACTOR as author
git commit -m "Update admin-console build artifacts

Automatically generated by admin-console build workflow.
Triggered by: @${GITHUB_ACTOR}"

# Push branch to origin
git push -u origin "${BRANCH_NAME}"

# Create pull request using GitHub CLI (authenticated with GITHUB_TOKEN)
gh pr create \
  --title "Update admin-console build artifacts" \
  --body "This PR was automatically generated to update the admin-console build artifacts.

**Details:**
- Built from commit: \`${GITHUB_SHA}\`
- Triggered by: @${GITHUB_ACTOR}
- Branch: \`${BRANCH_NAME}\`

Please review and merge to update the admin console on master." \
  --base master \
  --head "${BRANCH_NAME}"
