-- Update display_name for all event types
UPDATE event_type SET display_name = 'Daily digest' WHERE name = 'aggregation';
UPDATE event_type SET display_name = 'Vulnerability with known exploit identified' WHERE name = 'any-cve-known-exploit';
UPDATE event_type SET display_name = 'Integration availability status changed' WHERE name = 'availability-status';
UPDATE event_type SET display_name = 'Capacity Management' WHERE name = 'capacity-management';
UPDATE event_type SET display_name = 'Cluster Access' WHERE name = 'cluster-access';
UPDATE event_type SET display_name = 'Cluster Add-on' WHERE name = 'cluster-add-on';
UPDATE event_type SET display_name = 'Cluster Configuration' WHERE name = 'cluster-configuration';
UPDATE event_type SET display_name = 'Cluster Lifecycle' WHERE name = 'cluster-lifecycle';
UPDATE event_type SET display_name = 'Cluster Networking' WHERE name = 'cluster-networking';
UPDATE event_type SET display_name = 'Cluster Ownership' WHERE name = 'cluster-ownership';
UPDATE event_type SET display_name = 'Cluster Scaling' WHERE name = 'cluster-scaling';
UPDATE event_type SET display_name = 'Cluster Security' WHERE name = 'cluster-security';
UPDATE event_type SET display_name = 'Cluster Subscription' WHERE name = 'cluster-subscription';
UPDATE event_type SET display_name = 'Cluster Update' WHERE name = 'cluster-update';
UPDATE event_type SET display_name = 'Stale cost management data' WHERE name = 'cm-operator-stale';
UPDATE event_type SET display_name = 'System is non compliant to SCAP policy' WHERE name = 'compliance-below-threshold';
UPDATE event_type SET display_name = 'Custom default access group updated' WHERE name = 'custom-default-access-updated';
UPDATE event_type SET display_name = 'Customer Support' WHERE name = 'customer-support';
UPDATE event_type SET display_name = 'Custom role created' WHERE name = 'custom-role-created';
UPDATE event_type SET display_name = 'Custom role deleted' WHERE name = 'custom-role-deleted';
UPDATE event_type SET display_name = 'Custom role updated' WHERE name = 'custom-role-updated';
UPDATE event_type SET display_name = 'Deactivated recommendation' WHERE name = 'deactivated-recommendation';
UPDATE event_type SET display_name = 'Detected malware' WHERE name = 'detected-malware';
UPDATE event_type SET display_name = 'Task cancelled' WHERE name = 'executed-task-cancelled';
UPDATE event_type SET display_name = 'Executed task completed' WHERE name = 'executed-task-completed';
UPDATE event_type SET display_name = 'Task started' WHERE name = 'executed-task-started';
UPDATE event_type SET display_name = 'General communication' WHERE name = 'general-communication';
UPDATE event_type SET display_name = 'General Notification' WHERE name = 'general-notification';
UPDATE event_type SET display_name = 'Group created' WHERE name = 'group-created';
UPDATE event_type SET display_name = 'Group deleted' WHERE name = 'group-deleted';
UPDATE event_type SET display_name = 'Group updated' WHERE name = 'group-updated';
UPDATE event_type SET display_name = 'Integration disabled' WHERE name = 'integration-disabled';
UPDATE event_type SET display_name = 'Integration Test' WHERE name = 'integration-test';
UPDATE event_type SET display_name = 'Task job cancelled' WHERE name = 'job-cancelled';
UPDATE event_type SET display_name = 'Task job completed' WHERE name = 'job-completed';
UPDATE event_type SET display_name = 'Job failed' WHERE name = 'job-failed';
UPDATE event_type SET display_name = 'Task job started' WHERE name = 'job-started';
UPDATE event_type SET display_name = 'Missing OpenShift cost model' WHERE name = 'missing-cost-model';
UPDATE event_type SET display_name = 'New advisory' WHERE name = 'new-advisory';
UPDATE event_type SET display_name = 'New vulnerability with CVSS >= 7.0' WHERE name = 'new-cve-cvss';
UPDATE event_type SET display_name = 'New vulnerability containing security rule' WHERE name = 'new-cve-security-rule';
UPDATE event_type SET display_name = 'New vulnerability with critical severity' WHERE name = 'new-cve-severity';
UPDATE event_type SET display_name = 'New recommendation' WHERE name = 'new-recommendation';
UPDATE event_type SET display_name = 'Subscription Bug Fixes' WHERE name = 'new-subscription-bugfix-errata';
UPDATE event_type SET display_name = 'Subscription Enhancements' WHERE name = 'new-subscription-enhancement-errata';
UPDATE event_type SET display_name = 'Subscription Security Updates' WHERE name = 'new-subscription-security-errata';
UPDATE event_type SET display_name = 'New suggestion' WHERE name = 'new-suggestion';
UPDATE event_type SET display_name = 'New system registered' WHERE name = 'new-system-registered';
UPDATE event_type SET display_name = 'Notify customer environment is ready' WHERE name = 'notify-customer-provision-success';
UPDATE event_type SET display_name = 'Default access group has changed to custom default access' WHERE name = 'platform-default-group-turned-into-custom';
UPDATE event_type SET display_name = 'Policy report failed to upload' WHERE name = 'report-upload-failed';
UPDATE event_type SET display_name = 'Access requested' WHERE name = 'request-access';
UPDATE event_type SET display_name = 'Resolved recommendation' WHERE name = 'resolved-recommendation';
UPDATE event_type SET display_name = 'New Red Hat role added to default access group' WHERE name = 'rh-new-role-added-to-default-access';
UPDATE event_type SET display_name = 'New Red Hat role available' WHERE name = 'rh-new-role-available';
UPDATE event_type SET display_name = 'New TAM access request created' WHERE name = 'rh-new-tam-request-created';
UPDATE event_type SET display_name = 'Red Hat role not in default access group updated' WHERE name = 'rh-non-platform-default-role-updated';
UPDATE event_type SET display_name = 'Red Hat role in default access group updated' WHERE name = 'rh-platform-default-role-updated';
UPDATE event_type SET display_name = 'Red Hat role removed from default access group' WHERE name = 'rh-role-removed-from-default-access';
UPDATE event_type SET display_name = 'System became stale' WHERE name = 'system-became-stale';
UPDATE event_type SET display_name = 'System deleted' WHERE name = 'system-deleted';
UPDATE event_type SET display_name = 'Validation error' WHERE name = 'validation-error';
