####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
###

# Build the project
FROM registry.access.redhat.com/ubi9/openjdk-25:latest@sha256:68f712c440bccc81af8a1935dda4beff4fbed6466f4037f6d1437c0f455328bc AS build
USER root
COPY . /home/jboss
WORKDIR /home/jboss
RUN ./mvnw -s .mvn/settings.xml clean package -Dmaven.test.skip -Dcheckstyle.skip -pl :notifications-connector-microsoft-teams -am --no-transfer-progress

# Build the container
FROM registry.access.redhat.com/ubi9/openjdk-25-runtime:latest@sha256:c8bcc76dfc2ccf122bb7e2b82db7ae9de99a5276e495bcde9efbfa938dd5e3f7

# Update the base image packages
USER root
# See https://www.mankier.com/8/microdnf
RUN microdnf upgrade --refresh --nodocs --setopt=install_weak_deps=0 -y
RUN microdnf clean all
USER jboss

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError"

# Konflux preflight check requires a license
COPY --from=build /home/jboss/LICENSE.txt /licenses/LICENSE

# Use four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 /home/jboss/connector-microsoft-teams/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /home/jboss/connector-microsoft-teams/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /home/jboss/connector-microsoft-teams/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /home/jboss/connector-microsoft-teams/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTIONS -jar /deployments/quarkus-run.jar"]
