####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
###

# Build the project
FROM registry.access.redhat.com/ubi9/openjdk-21:latest@sha256:645710be17ff582b0f2eb5d52f572556a2b73f4367290548bbc89431213e3ece AS build
USER root
COPY . /home/jboss
WORKDIR /home/jboss
RUN ./mvnw -s .mvn/settings.xml clean package -Dmaven.test.skip -Dcheckstyle.skip -pl :notifications-connector-splunk -am --no-transfer-progress

# Build the container
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest@sha256:908540a90db3dea9dcc8b80de84c9d44ced2dd328d3ed36930b0b04ad8a0f4e8

# Update the base image packages
USER root
# See https://www.mankier.com/8/microdnf
RUN microdnf upgrade --refresh --nodocs --setopt=install_weak_deps=0 -y
RUN microdnf clean all
USER jboss

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError"

# Konflux preflight check requires a license
COPY --from=build /home/jboss/LICENSE.txt /licenses/LICENSE

# Use four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 /home/jboss/connector-splunk/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /home/jboss/connector-splunk/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /home/jboss/connector-splunk/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /home/jboss/connector-splunk/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTIONS -jar /deployments/quarkus-run.jar"]
