####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
###

# Build the project
FROM registry.access.redhat.com/ubi9/openjdk-21:latest@sha256:cc8a30e9181b0135e6657ca3b824d7b32e4c7f6a664769ef641d4f7031339564 AS build
USER root
COPY . /home/jboss
WORKDIR /home/jboss
RUN ./mvnw clean package -Dmaven.test.skip -Dcheckstyle.skip -pl :notifications-connector-drawer -am --no-transfer-progress

# Build the container
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest@sha256:ff0a095f96c1823453008aef23b98868f3bf723fa0497d68c2fb9b1a27884064

# Update the base image packages
USER root
# See https://www.mankier.com/8/microdnf
RUN microdnf upgrade --refresh --nodocs --setopt=install_weak_deps=0 -y
RUN microdnf clean all
USER jboss

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError"

# Konflux preflight check requires a license
COPY --from=build /home/jboss/LICENSE.txt /licenses/LICENSE

# Use four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 /home/jboss/connector-drawer/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /home/jboss/connector-drawer/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /home/jboss/connector-drawer/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /home/jboss/connector-drawer/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTIONS -jar /deployments/quarkus-run.jar"]
