####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
###

# Build the project
FROM registry.access.redhat.com/ubi9/openjdk-21:latest@sha256:3e281b9da807321a35231b3ba543eeff9b7c736ece3f27a914303d3b8f9da0e1 AS build
USER root
COPY . /home/jboss
WORKDIR /home/jboss
RUN ./mvnw -s .mvn/settings.xml clean package -Dmaven.test.skip -Dcheckstyle.skip -pl :notifications-connector-email -am --no-transfer-progress

# Build the container
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest@sha256:e11f680f46044d1679caad669702624ac327a7169952f2d69ba6e6276ab98c81

# Update the base image packages
USER root
# See https://www.mankier.com/8/microdnf
RUN microdnf upgrade --refresh --nodocs --setopt=install_weak_deps=0 -y
RUN microdnf clean all
# Add RedHat CAs on OS truststore (check https://certs.corp.redhat.com/ for more details)
COPY --from=build /home/jboss/recipients-resolver/src/main/resources/mtls-ca-validators.crt /etc/pki/ca-trust/source/anchors/mtls-ca-validators.crt
RUN update-ca-trust

USER jboss

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError"

# Konflux preflight check requires a license
COPY --from=build /home/jboss/LICENSE.txt /licenses/LICENSE

# Use four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 /home/jboss/connector-email/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /home/jboss/connector-email/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /home/jboss/connector-email/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /home/jboss/connector-email/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTIONS -jar /deployments/quarkus-run.jar"]
