---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: notifications-engine
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: notifications-engine
    labels:
      app: notifications-engine
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - ingress
    - notifications-backend
    - notifications-recipients-resolver
    optionalDependencies:
    - export-service
    database:
      sharedDbAppName: notifications-backend
    featureFlags: true
    kafkaTopics:
    - topicName: platform.notifications.connector.email.high.volume
      partitions: 6
      replicas: 3
    - topicName: platform.notifications.ingress
      partitions: 3
      replicas: 3
    - topicName: platform.notifications.tocamel
      partitions: 3
      replicas: 3
    - topicName: platform.notifications.fromcamel
      partitions: 3
      replicas: 3
    - topicName: platform.export.requests
      partitions: 3
      replicas: 3
    - topicName: platform.chrome
      partitions: 3
      replicas: 3
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumes:
        - name: rds-client-ca
          emptyDir: {}
        volumeMounts:
        - name: rds-client-ca
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        env:
        - name: ENV_BASE_URL
          value: ${ENV_BASE_URL}
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: HOST_NAME
          value: ${HOSTNAME}
        - name: MP_MESSAGING_INCOMING_FROMCAMEL_ENABLED
          value: ${MP_MESSAGING_INCOMING_FROMCAMEL_ENABLED}
        - name: MP_MESSAGING_INCOMING_INGRESS_ENABLED
          value: ${MP_MESSAGING_INCOMING_INGRESS_ENABLED}
        - name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_INTERVAL_MS
          value: ${MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_INTERVAL_MS}
        - name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_RECORDS
          value: ${MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_RECORDS}
        - name: MP_MESSAGING_INCOMING_INGRESS_THROTTLED_UNPROCESSED_RECORD_MAX_AGE_MS
          value: ${MP_MESSAGING_INCOMING_INGRESS_THROTTLED_UNPROCESSED_RECORD_MAX_AGE_MS}
        - name: MP_MESSAGING_OUTGOING_TOCAMEL_ENABLED
          value: ${MP_MESSAGING_OUTGOING_TOCAMEL_ENABLED}
        - name: MP_MESSAGING_OUTGOING_TOCAMEL_MAX_REQUEST_SIZE
          value: ${MP_MESSAGING_OUTGOING_TOCAMEL_MAX_REQUEST_SIZE}
        - name: NOTIFICATIONS_AGGREGATION_MAX_PAGE_SIZE
          value: ${NOTIFICATIONS_AGGREGATION_MAX_PAGE_SIZE}
        - name: NOTIFICATIONS_EMAIL_HCC_SENDER_NAME_ENABLED
          value: ${NOTIFICATIONS_EMAIL_HCC_SENDER_NAME_ENABLED}
        - name: NOTIFICATIONS_EMAILS_ONLY_MODE_ENABLED
          value: ${NOTIFICATIONS_EMAILS_ONLY_MODE_ENABLED}
        - name: NOTIFICATIONS_EMAIL_SENDER_HYBRID_CLOUD_CONSOLE
          value: ${NOTIFICATIONS_EMAIL_SENDER_HYBRID_CLOUD_CONSOLE}
        - name: NOTIFICATIONS_EMAIL_SENDER_OPENSHIFT_STAGE
          value: ${NOTIFICATIONS_EMAIL_SENDER_OPENSHIFT_STAGE}
        - name: NOTIFICATIONS_EMAIL_SENDER_OPENSHIFT_PROD
          value: ${NOTIFICATIONS_EMAIL_SENDER_OPENSHIFT_PROD}
        - name: NOTIFICATIONS_EVENT_CONSUMER_CORE_THREAD_POOL_SIZE
          value: ${NOTIFICATIONS_EVENT_CONSUMER_CORE_THREAD_POOL_SIZE}
        - name: NOTIFICATIONS_EVENT_CONSUMER_MAX_THREAD_POOL_SIZE
          value: ${NOTIFICATIONS_EVENT_CONSUMER_MAX_THREAD_POOL_SIZE}
        - name: NOTIFICATIONS_EVENT_CONSUMER_KEEP_ALIVE_TIME_SECONDS
          value: ${NOTIFICATIONS_EVENT_CONSUMER_KEEP_ALIVE_TIME_SECONDS}
        - name: NOTIFICATIONS_EVENT_CONSUMER_QUEUE_CAPACITY
          value: ${NOTIFICATIONS_EVENT_CONSUMER_QUEUE_CAPACITY}
        - name: NOTIFICATIONS_KAFKA_CONSUMED_TOTAL_CHECKER_ENABLED
          value: ${KAFKA_CONSUMED_TOTAL_CHECKER_ENABLED}
        - name: NOTIFICATIONS_KAFKA_CONSUMED_TOTAL_CHECKER_INITIAL_DELAY
          value: ${KAFKA_CONSUMED_TOTAL_CHECKER_INITIAL_DELAY}
        - name: NOTIFICATIONS_KAFKA_CONSUMED_TOTAL_CHECKER_PERIOD
          value: ${KAFKA_CONSUMED_TOTAL_CHECKER_PERIOD}
        - name: NOTIFICATIONS_KAFKA_OUTGOING_HIGH_VOLUME_TOPIC_ENABLED
          value: ${NOTIFICATIONS_KAFKA_OUTGOING_HIGH_VOLUME_TOPIC_ENABLED}
        - name: QUARKUS_HIBERNATE_ORM_LOG_SQL
          value: ${QUARKUS_HIBERNATE_ORM_LOG_SQL}
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CATEGORY__COM_REDHAT_CLOUD_NOTIFICATIONS__LEVEL
          value: ${NOTIFICATIONS_LOG_LEVEL}
        - name: QUARKUS_LOG_CATEGORY__IO_SMALLRYE_REACTIVE_MESSAGING__LEVEL
          value: ${IO_SMALLRYE_REACTIVE_MESSAGING_LOG_LEVEL}
        - name: QUARKUS_LOG_CATEGORY__ORG_APACHE_KAFKA_CLIENTS__LEVEL
          value: ${KAFKA_CLIENT_LOG_LEVEL}
        - name: QUARKUS_LOG_CLOUDWATCH_API_CALL_TIMEOUT
          value: ${QUARKUS_LOG_CLOUDWATCH_API_CALL_TIMEOUT}
        - name: QUARKUS_LOG_CLOUDWATCH_BATCH_PERIOD
          value: ${QUARKUS_LOG_CLOUDWATCH_BATCH_PERIOD}
        - name: QUARKUS_LOG_CLOUDWATCH_BATCH_SIZE
          value: ${QUARKUS_LOG_CLOUDWATCH_BATCH_SIZE}
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_MAX_QUEUE_SIZE
          value: ${QUARKUS_LOG_CLOUDWATCH_MAX_QUEUE_SIZE}
        - name: QUARKUS_LOG_CLOUDWATCH_SERVICE_ENVIRONMENT
          value: ${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: ${SENTRY_DSN}${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
        - name: NOTIFICATIONS_USE_DEFAULT_TEMPLATE
          value: ${NOTIFICATIONS_USE_DEFAULT_TEMPLATE}
        - name: NOTIFICATIONS_USE_SECURED_EMAIL_TEMPLATES_ENABLED
          value: ${NOTIFICATIONS_USE_SECURED_EMAIL_TEMPLATES_ENABLED}
        - name: MP_MESSAGING_INCOMING_EXPORTREQUESTS_ENABLED
          value: ${NOTIFICATIONS_EXPORT_SERVICE_ENABLED}
        - name: MP_MESSAGING_INCOMING_EXPORTREQUESTS_MAX_POLL_INTERVAL_MS
          value: ${MP_MESSAGING_INCOMING_EXPORTREQUESTS_MAX_POLL_INTERVAL_MS}
        - name: MP_MESSAGING_INCOMING_EXPORTREQUESTS_MAX_POLL_RECORDS
          value: ${MP_MESSAGING_INCOMING_EXPORTREQUESTS_MAX_POLL_RECORDS}
        - name: EXPORT_SERVICE_PSK
          valueFrom:
            secretKeyRef:
              name: export-service-psk
              key: psk
              optional: true
        - name: QUARKUS_LOG_CATEGORY__COM_REDHAT_CLOUD_NOTIFICATIONS_EXPORTS_EXPORTEVENTLISTENER__LEVEL
          value: ${EXPORT_EVENT_LISTENER_LOG_LEVEL}
        - name: QUARKUS_REST_CLIENT_LOGGING_SCOPE
          value: ${QUARKUS_REST_CLIENT_LOGGING_SCOPE}
        - name: QUARKUS_LOG_CATEGORY__ORG_JBOSS_RESTEASY_REACTIVE_CLIENT_LOGGING__LEVEL
          value: ${QUARKUS_LOG_CATEGORY__ORG_JBOSS_RESTEASY_REACTIVE_CLIENT_LOGGING__LEVEL}
        - name: NOTIFICATIONS_DRAWER_ENABLED
          value: ${NOTIFICATIONS_DRAWER_ENABLED}
        - name: NOTIFICATIONS_ASYNC_AGGREGATION_ENABLED
          value: ${NOTIFICATIONS_ASYNC_AGGREGATION_ENABLED}
        - name: NOTIFICATIONS_UNLEASH_ENABLED
          value: ${NOTIFICATIONS_UNLEASH_ENABLED}
        - name: QUARKUS_UNLEASH_ACTIVE
          value: ${NOTIFICATIONS_UNLEASH_ENABLED}
        - name: PROCESSOR_CONNECTORS_MAX_SERVER_ERRORS
          value: ${PROCESSOR_CONNECTORS_MAX_SERVER_ERRORS}
        - name: PROCESSOR_CONNECTORS_MIN_DELAY_SINCE_FIRST_SERVER_ERROR
          value: ${PROCESSOR_CONNECTORS_MIN_DELAY_SINCE_FIRST_SERVER_ERROR}
        - name: NOTIFICATIONS_USE_OCM_REFACTORED_TEMPLATES
          value: ${NOTIFICATIONS_USE_OCM_REFACTORED_TEMPLATES}
parameters:
- name: CLOUDWATCH_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
- name: CPU_LIMIT
  description: CPU limit
  value: 500m
- name: CPU_REQUEST
  description: CPU request
  value: 500m
- name: ENV_BASE_URL
  value: https://console.redhat.com
  description: The environment's base URL
- name: ENV_NAME
  description: ClowdEnvironment name (ephemeral, stage, prod)
  required: true
- name: IMAGE
  description: Image URL
  value: quay.io/cloudservices/notifications-engine
- name: IMAGE_TAG
  value: latest
- name: KAFKA_CONSUMED_TOTAL_CHECKER_ENABLED
  description: Is the Kafka records consumed total check included in the global health check?
  value: "false"
- name: KAFKA_CONSUMED_TOTAL_CHECKER_INITIAL_DELAY
  description: Delay after the server startup before the first check is performed
  value: 5m
- name: KAFKA_CONSUMED_TOTAL_CHECKER_PERIOD
  description: Time between two Kafka records consumed total checks
  value: 5m
- name: MEMORY_LIMIT
  description: Memory limit
  value: 500Mi
- name: MEMORY_REQUEST
  description: Memory request
  value: 250Mi
- name: MIN_REPLICAS
  value: "3"
- name: MP_MESSAGING_INCOMING_FROMCAMEL_ENABLED
  value: "true"
- name: MP_MESSAGING_INCOMING_INGRESS_ENABLED
  value: "true"
- name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_INTERVAL_MS
  description: Maximum delay between invocations of poll()
  value: "300000"
- name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_RECORDS
  description: Maximum number of records returned in a single call to poll()
  value: "500"
- name: MP_MESSAGING_INCOMING_INGRESS_THROTTLED_UNPROCESSED_RECORD_MAX_AGE_MS
  description: Max age in milliseconds that an unprocessed message can be before the connector is marked as unhealthy
  value: "60000"
- name: MP_MESSAGING_OUTGOING_TOCAMEL_ENABLED
  value: "true"
- name: MP_MESSAGING_OUTGOING_TOCAMEL_MAX_REQUEST_SIZE
  description: Maximum size of a request (which can include several messages) in bytes (default is 1048576). Uncompressed messages that exceed this value will trigger a RecordTooLargeException, even if their size after compression is lower than the value.
  value: "10485760"
- name: NOTIFICATIONS_AGGREGATION_MAX_PAGE_SIZE
  description: Maximum number of aggregation records loaded from the DB at once
  value: "100"
- name: NOTIFICATIONS_EMAIL_HCC_SENDER_NAME_ENABLED
  value: "false"
- name: NOTIFICATIONS_EMAILS_ONLY_MODE_ENABLED
  description: When this is true, all integration types except emails are disabled
  value: "true"
- name: NOTIFICATIONS_EMAIL_SENDER_HYBRID_CLOUD_CONSOLE
  description: The email sender address for the Red Hat Hybrid Cloud Console.
  value: "\"Red Hat Hybrid Cloud Console\" noreply@redhat.com"
- name: NOTIFICATIONS_EMAIL_SENDER_OPENSHIFT_STAGE
  description: The email sender address for the OpenShift domain in stage.
  value: "\"Red Hat OpenShift (staging)\" noreply@redhat.com"
- name: NOTIFICATIONS_EMAIL_SENDER_OPENSHIFT_PROD
  description: The email sender address for the OpenShift domain in production.
  value: "\"Red Hat OpenShift\" noreply@redhat.com"
- name: NOTIFICATIONS_EVENT_CONSUMER_CORE_THREAD_POOL_SIZE
  description: Number of threads to keep in the pool, even if they are idle.
  value: "10"
- name: NOTIFICATIONS_EVENT_CONSUMER_MAX_THREAD_POOL_SIZE
  description: Maximum number of threads to allow in the pool.
  value: "10"
- name: NOTIFICATIONS_EVENT_CONSUMER_KEEP_ALIVE_TIME_SECONDS
  description: Maximum time that excess idle threads will wait for new tasks before terminating.
  value: "60"
- name: NOTIFICATIONS_EVENT_CONSUMER_QUEUE_CAPACITY
  description: Capacity of the blocking Kafka messages queue.
  value: "1"
- name: NOTIFICATIONS_KAFKA_OUTGOING_HIGH_VOLUME_TOPIC_ENABLED
  description: Specifies whether the high volume topic is enabled in the engine or not.
  value: "false"
- name: NOTIFICATIONS_LOG_LEVEL
  description: Log level for com.redhat.cloud.notifications
  value: INFO
- name: NOTIFICATIONS_UNLEASH_ENABLED
  value: "false"
- name: QUARKUS_HIBERNATE_ORM_LOG_SQL
  value: "false"
- name: QUARKUS_LOG_CLOUDWATCH_API_CALL_TIMEOUT
  description: Amount of time to allow the CloudWatch client to complete the execution of an API call expressed with the ISO-8601 duration format PnDTnHnMn.nS.
  value: PT30S
- name: QUARKUS_LOG_CLOUDWATCH_BATCH_PERIOD
  description: Period between two batch executions. Defaults to 5s.
  value: 5s
- name: QUARKUS_LOG_CLOUDWATCH_BATCH_SIZE
  description: Number of log events sent to CloudWatch per batch. Defaults to 10,000 which is the maximum number of log events per batch allowed by CloudWatch.
  value: "10000"
- name: QUARKUS_LOG_CLOUDWATCH_MAX_QUEUE_SIZE
  description: Optional maximum size of the log events queue. If this is not set, the queue will have a capacity of Integer#MAX_VALUE.
  value: "100000"
- name: SENTRY_DSN
  description: The DSN to push data to Sentry — i.e. https://public_key@host/project_id?environment=
- name: SENTRY_ENABLED
  description: Enable Sentry (or not)
  value: "false"
- name: NOTIFICATIONS_USE_DEFAULT_TEMPLATE
  value: "false"
- name: NOTIFICATIONS_USE_SECURED_EMAIL_TEMPLATES_ENABLED
  value: "true"
- name: IO_SMALLRYE_REACTIVE_MESSAGING_LOG_LEVEL
  value: INFO
- name: KAFKA_CLIENT_LOG_LEVEL
  value: WARN
- name: NOTIFICATIONS_EXPORT_SERVICE_ENABLED
  description: Enables the integration with the export service.
  value: "false"
- name: MP_MESSAGING_INCOMING_EXPORTREQUESTS_MAX_POLL_INTERVAL_MS
  description: Maximum delay between invocations of poll()
  value: "300000"
- name: MP_MESSAGING_INCOMING_EXPORTREQUESTS_MAX_POLL_RECORDS
  description: Maximum number of records returned in a single call to poll()
  value: "500"
- name: EXPORT_EVENT_LISTENER_LOG_LEVEL
  description: The log level for the export service's event listener.
  value: "INFO"
- name: QUARKUS_REST_CLIENT_LOGGING_SCOPE
  description: When set to 'request-response', rest-client will log the request and response contents
  value: ""
- name: QUARKUS_LOG_CATEGORY__ORG_JBOSS_RESTEASY_REACTIVE_CLIENT_LOGGING__LEVEL
  description: When QUARKUS_REST_CLIENT_LOGGING_SCOPE is set to 'request-response', this logger level needs to be set to DEBUG
  value: INFO
- name: NOTIFICATIONS_DRAWER_ENABLED
  value: "false"
- name: NOTIFICATIONS_ASYNC_AGGREGATION_ENABLED
  value: "false"
- name: PROCESSOR_EMAIL_AGGREGATION_USE_RECIPIENTS_RESOLVER_CLOWDAPP_ENABLED
  value: "true"
- name: PROCESSOR_CONNECTORS_MAX_SERVER_ERRORS
  description: max accepted number of errors before an endpoint is eligible to be disabled
  value: "10"
- name: PROCESSOR_CONNECTORS_MIN_DELAY_SINCE_FIRST_SERVER_ERROR
  description: min delay since the first error before an endpoint is eligible to be disabled
  value: P2D
- name: NOTIFICATIONS_USE_OCM_REFACTORED_TEMPLATES
  value: "false"
