---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: notifications-backend
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: notifications-backend
    labels:
      app: notifications-backend
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - rbac
    - ingress
    database:
      name: notifications_backend
      version: 12
    kafkaTopics:
    - topicName: platform.notifications.ingress
      partitions: 3
      replicas: 3
    - topicName: platform.notifications.tocamel
      partitions: 3
      replicas: 3
    - topicName: platform.notifications.fromcamel
      partitions: 3
      replicas: 3
    - topicName: platform.notifications.aggregation
      partitions: 2
      replicas: 3
    testing:
      iqePlugin: notifications
    deployments:
    - name: notifications-backend
      minReplicas: ${{MIN_REPLICAS}}
      web: true
      podSpec:
        image: ${BACKEND_IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${BACKEND_CPU_REQUEST}
            memory: ${BACKEND_MEMORY_REQUEST}
          limits:
            cpu: ${BACKEND_CPU_LIMIT}
            memory: ${BACKEND_MEMORY_LIMIT}
        volumes:
        - name: rds-client-ca
          emptyDir: {}
        volumeMounts:
        - name: rds-client-ca
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_INTERVAL_MS
          value: ${MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_INTERVAL_MS}
        - name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_RECORDS
          value: ${MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_RECORDS}
        - name: PROCESSOR_EMAIL_BOP_APITOKEN
          valueFrom:
            secretKeyRef:
              name: backoffice
              key: token
        - name: PROCESSOR_EMAIL_BOP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backoffice
              key: client-id
        - name: PROCESSOR_EMAIL_BOP_ENV
          value: ${BACKOFFICE_CLIENT_ENV}
        - name: PROCESSOR_EMAIL_BOP_URL
          value: https://${BACKOFFICE_HOST}/v1/sendEmails
        - name: PROCESSOR_EMAIL_NO_REPLY
          value: ${PROCESSOR_EMAIL_NO_REPLY}
        - name: RBAC_AUTHENTICATION_MP_REST_READTIMEOUT
          value: ${RBAC_AUTHENTICATION_READ_TIMEOUT}
        - name: RBAC_S2S_MP_REST_READTIMEOUT
          value: ${RBAC_S2S_READ_TIMEOUT}
        - name: RBAC_SERVICE_TO_SERVICE_APPLICATION
          value: ${RBAC_SERVICE_TO_SERVICE_APP}
        - name: RBAC_SERVICE_TO_SERVICE_SECRET_MAP
          valueFrom:
            secretKeyRef:
              name: rbac-psks
              key: psks.json
        - name: RECIPIENT_PROVIDER_RBAC_ELEMENTS_PER_PAGE
          value: ${RECIPIENT_PROVIDER_RBAC_ELEMENTS_PER_PAGE}
        - name: QUARKUS_CACHE_CAFFEINE_RBAC_RECIPIENT_USERS_PROVIDER_GET_USERS_EXPIRE_AFTER_WRITE
          value: ${RBAC_USERS_RETENTION_DELAY}
        - name: QUARKUS_CACHE_CAFFEINE_RBAC_RECIPIENT_USERS_PROVIDER_GET_GROUP_USERS_EXPIRE_AFTER_WRITE
          value: ${RBAC_GROUP_USERS_RETENTION_DELAY}
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CATEGORY__COM_REDHAT_CLOUD_NOTIFICATIONS__LEVEL
          value: ${NOTIFICATIONS_LOG_LEVEL}
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_LOG_STREAM_NAME
          value: ${HOSTNAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: https://3ff0dbd8017a4750a1d92055a1685263@o271843.ingest.sentry.io/5440905?environment=${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
    jobs:
    - name: notifications-aggregator
      schedule: ${CRONTAB_AGGREGATION_JOB}
      suspend: ${{SUSPEND_AGGREGATION_JOB}}
      startingDeadlineSeconds: ${{STARTING_DEADLINE}}
      successfulJobsHistoryLimit: 7
      failedJobsHistoryLimit: 7
      concurrencyPolicy: Forbid
      restartPolicy: OnFailure
      podSpec:
        image: ${AGGREGATOR_IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${AGGREGATOR_CPU_REQUEST}
            memory: ${AGGREGATOR_MEMORY_REQUEST}
          limits:
            cpu: ${AGGREGATOR_CPU_LIMIT}
            memory: ${AGGREGATOR_MEMORY_LIMIT}
        volumes:
        - name: rds-client-ca
          emptyDir: {}
        volumeMounts:
        - name: rds-client-ca
          mountPath: /tmp
        env:
        - name: NOTIFICATIONS_AGGREGATOR_EMAIL_SUBSCRIPTION_PERIODIC_CRON_ENABLED
          value: ${CRONJOB_ENABLED}
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CATEGORY__COM_REDHAT_CLOUD_NOTIFICATIONS__LEVEL
          value: ${NOTIFICATIONS_LOG_LEVEL}
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_LOG_STREAM_NAME
          value: ${HOSTNAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: https://39032857c8214cedaf226c4a26709b5b@o271843.ingest.sentry.io/5987783?environment=${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
parameters:
- name: AGGREGATOR_CPU_LIMIT
  description: Aggregator CPU limit on ephemeral
  value: 500m
- name: AGGREGATOR_CPU_REQUEST
  description: Aggregator CPU request on ephemeral
  value: 500m
- name: AGGREGATOR_IMAGE
  description: Aggregator image URL
  value: quay.io/cloudservices/notifications-aggregator
- name: AGGREGATOR_MEMORY_LIMIT
  description: Aggregator memory limit on ephemeral
  value: 500Mi
- name: AGGREGATOR_MEMORY_REQUEST
  description: Aggregator memory request on ephemeral
  value: 250Mi
- name: BACKEND_CPU_LIMIT
  description: Backend CPU limit on ephemeral
  value: 500m
- name: BACKEND_CPU_REQUEST
  description: Backend CPU request on ephemeral
  value: 500m
- name: BACKEND_IMAGE
  description: Backend image URL
  value: quay.io/cloudservices/notifications-backend
- name: BACKEND_MEMORY_LIMIT
  description: Backend memory limit on ephemeral
  value: 500Mi
- name: BACKEND_MEMORY_REQUEST
  description: Backend memory request on ephemeral
  value: 250Mi
- name: BACKOFFICE_CLIENT_ENV
  description: Back-office client environment
  value: qa
- name: BACKOFFICE_HOST
  description: backoffice URL
  value: backoffice-proxy-insights-services.ext.us-east.aws.preprod.paas.redhat.com
- name: CLOUDWATCH_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
- name: CRONTAB_AGGREGATION_JOB
  value: "0 0 * * *"
- name: CRONJOB_ENABLED
  description: Enable the cron job
  value: "false"
- name: ENV_NAME
  description: ClowdEnvironment name (stage, prod, ephemeral)
  required: true
- name: IMAGE_TAG
  value: latest
- name: MIN_REPLICAS
  value: "1"
- name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_INTERVAL_MS
  description: Maximum delay between invocations of poll()
  value: "300000"
- name: MP_MESSAGING_INCOMING_INGRESS_MAX_POLL_RECORDS
  description: Maximum number of records returned in a single call to poll()
  value: "500"
- name: NOTIFICATIONS_LOG_LEVEL
  description: Log level for com.redhat.cloud.notifications
  value: INFO
- name: PROCESSOR_EMAIL_NO_REPLY
  description: Email address
  value: no-reply@redhat.com
- name: RBAC_AUTHENTICATION_READ_TIMEOUT
  description: Delay in milliseconds before an RBAC authentication query is interrupted
  value: "2000"
- name: RBAC_S2S_READ_TIMEOUT
  description: Delay in milliseconds before an RBAC S2S query is interrupted
  value: "120000"
- name : RBAC_GROUP_USERS_RETENTION_DELAY
  description: RBAC group users data cache retention delay. It must be expressed with the ISO-8601 duration format PnDTnHnMn.nS.
  value: PT10M
- name: RBAC_SERVICE_TO_SERVICE_APP
  description: RBAC application name to use for service-to-service communication
  value: notifications
- name : RBAC_USERS_RETENTION_DELAY
  description: RBAC users data cache retention delay. It must be expressed with the ISO-8601 duration format PnDTnHnMn.nS.
  value: PT10M
- name: RECIPIENT_PROVIDER_RBAC_ELEMENTS_PER_PAGE
  description: Limit value sent as a query param to the RBAC REST API while querying RBAC users.
  value: "1000"
- name: SENTRY_ENABLED
  description: Enable Sentry (or not)
  value: "false"
- name: STARTING_DEADLINE
  value: "300"
- name: SUSPEND_AGGREGATION_JOB
  description: Should the aggregation cron job be disabled?
  value: "false"
