---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: notifications-backend
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: notifications-backend
    labels:
      app: notifications-backend
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - notifications-engine
    - rbac
    database:
      name: notifications-backend
      version: 12
    testing:
      iqePlugin: notifications
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumes:
        - name: rds-client-ca
          emptyDir: {}
        volumeMounts:
        - name: rds-client-ca
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: NOTIFICATIONS_EPHEMERAL_DATA
          valueFrom:
            configMapKeyRef:
              name: notifications-ephemeral-data
              key: ephemeral_data.json
              optional: true
        - name: RBAC_AUTHENTICATION_MP_REST_READTIMEOUT
          value: ${RBAC_AUTHENTICATION_READ_TIMEOUT}
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CATEGORY__COM_REDHAT_CLOUD_NOTIFICATIONS__LEVEL
          value: ${NOTIFICATIONS_LOG_LEVEL}
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_LOG_STREAM_NAME
          value: ${HOSTNAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: https://3ff0dbd8017a4750a1d92055a1685263@o271843.ingest.sentry.io/5440905?environment=${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: notifications-db-cleaner-config
  data:
    clean.sh: |
      cat /notifications-db-cleaner/clean.sql | psql > /dev/null
    clean.sql: |
      CALL cleanEventLog();
      CALL cleanKafkaMessagesIds();
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: notifications-db-cleaner-cronjob
  spec:
    schedule: ${DB_CLEANER_SCHEDULE}
    suspend: ${{DISABLE_DB_CLEANER}}
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            volumes:
            - name: notifications-db-cleaner-volume
              configMap:
                name: notifications-db-cleaner-config
            containers:
            - name: notifications-db-cleaner
              image: quay.io/cloudservices/postgresql-rds:12-1
              restartPolicy: Never
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  cpu: 200m
                  memory: 200Mi
              volumeMounts:
              - name: notifications-db-cleaner-volume
                mountPath: /notifications-db-cleaner
              command: ['sh', '/notifications-db-cleaner/clean.sh']
              env:
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: notifications-backend-db
                    key: ${DB_SECRET_HOSTNAME_KEY}
              - name: PGDATABASE
                value: ${DB_NAME}
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: notifications-backend-db
                    key: ${DB_SECRET_USERNAME_KEY}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: notifications-backend-db
                    key: ${DB_SECRET_PASSWORD_KEY}
parameters:
- name: CLOUDWATCH_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
- name: CPU_LIMIT
  description: CPU limit
  value: 500m
- name: CPU_REQUEST
  description: CPU request
  value: 500m
- name: DB_CLEANER_SCHEDULE
  description: Execution time specified in cron format
  value: "*/10 * * * *"
- name: DB_NAME
  description: Database name used by the notifications-db-cleaner CronJob
  value: notifications_backend
- name: DB_SECRET_HOSTNAME_KEY
  description: Key of the hostname field in the notifications-backend-db secret
  value: db.host
- name: DB_SECRET_PASSWORD_KEY
  description: Key of the password field in the notifications-backend-db secret
  value: db.password
- name: DB_SECRET_USERNAME_KEY
  description: Key of the username field in the notifications-backend-db secret
  value: db.user
- name: DISABLE_DB_CLEANER
  description: Should the DB cleaner CronJob be disabled?
  value: "false"
- name: ENV_NAME
  description: ClowdEnvironment name (ephemeral, stage, prod)
  required: true
- name: IMAGE
  description: Image URL
  value: quay.io/cloudservices/notifications-backend
- name: IMAGE_TAG
  value: latest
- name: MEMORY_LIMIT
  description: Memory limit
  value: 500Mi
- name: MEMORY_REQUEST
  description: Memory request
  value: 250Mi
- name: MIN_REPLICAS
  value: "1"
- name: NOTIFICATIONS_LOG_LEVEL
  description: Log level for com.redhat.cloud.notifications
  value: INFO
- name: RBAC_AUTHENTICATION_READ_TIMEOUT
  description: Delay in milliseconds before an RBAC authentication query is interrupted
  value: "2000"
- name: SENTRY_ENABLED
  description: Enable Sentry (or not)
  value: "false"
