---
apiVersion: v1
kind: Template
metadata:
  name: notifications-backend
objects:
- apiVersion: v1
  kind: Secret # For ephemeral/local environment
  metadata:
    name: notifications-backend-secrets
    labels:
      app: notifications-backend
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: notifications-backend
    labels:
      app: notifications-backend
      clowdapp: notifications-backend
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: notifications
    deployments:
    - name: notifications-backend
      minReplicas: ${{MIN_REPLICAS}}
      web: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
        - name: CLOWDER_FILE
          value: ${CLOWDER_FILE}
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: RBAC_URL
          value: ${RBAC_SCHEME}://${RBAC_HOST}:${RBAC_PORT}
        - name: RBAC_MP_REST_URL
          value: ${RBAC_SCHEME}://${RBAC_HOST}:${RBAC_PORT}
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_LOGGING_ENABLED}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        volumes:
        - emptyDir: {}
          name: tmpdir
        volumeMounts:
        - mountPath: /tmp
          name: tmpdir
    kafkaTopics:
    - replicas: 3
      partitions: 64
      topicName: platform.notifications.ingress
    database:
      name: notifications
      version: 12
    optionalDependencies:
      - rbac
      - ingress

parameters:
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 500Mi
- name: CPU_REQUEST
  description: The cpu request
  value: 500m
- name: MEMORY_REQUEST
  description: The memory request
  value: 250Mi
- name: MIN_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/notifications-backend
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "false"
- description: ClowdEnv Name
  name: ENV_NAME
  required: true
- name: CLOWDER_FILE
  value: /cdapp/cdappconfig.json
  description: default path for cdappconfig file
- name: RBAC_HOST
  displayName: Rbac Service Host
  description: Host to use for the RBAC service URL.
  value: "rbac-service"
- name: RBAC_PORT
  displayName: Rbac Service Port
  description: Port to use for the RBAC service URL.
  value: "8000"
- name: RBAC_SCHEME
  displayName: Rbac Service Scheme
  description: Scheme to use for the RBAC service URL. Can be either http or https
  value: http
- name: CLOUDWATCH_LOGGING_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
