---
apiVersion: v1
kind: Template
metadata:
  name: notifications-acceptance
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: acceptance-iqe-${IMAGE_TAG}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        imagePullSecrets:
          - name: quay-cloudservices-pull
        containers:
          - image: quay.io/cloudservices/iqe-tests:latest
            imagePullPolicy: Always
            name: notifications-acceptance-iqe
            command:
              - iqe
              - tests
              - plugin
              - notifications
              - "-m"
              - stage_health
            env:
              - name: ENV_FOR_DYNACONF
                value: stage_gating
              - name: IQE_PLUGINS
                value: notifications
              - name: IQE_TESTS_LOCAL_CONF_PATH
                value: '/iqe-job-config'
            volumeMounts:
            - name: iqe-job-config-vol
              mountPath: /iqe-job-config
              readOnly: true
        volumes:
          - name: iqe-job-config-vol
            secret:
              secretName: iqe-testing-config

parameters:
- name: IMAGE_TAG
  value: ''
  required: true