---
apiVersion: v1
kind: Template
metadata:
  name: notifications-do-nothing
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: notifications-do-nothing-job-${IMAGE_TAG}-${JOBID}
    annotations:
      ignore-check.kube-linter.io/unset-cpu-requirements : "Not required for this job that does nothing"  
      ignore-check.kube-linter.io/unset-memory-requirements : "Not required for this job that does nothing"  
  spec:
    template:
      spec:
        containers:
        - name: notifications-do-nothing
          image: quay.io/app-sre/ubi8-ubi-minimal:8.6-902
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        restartPolicy: Never
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: JOBID
  generate: expression
  from: "[0-9a-f]{7}"
