---
apiVersion: v1
kind: Template
metadata:
  name: notifications-do-nothing
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: notifications-do-nothing-job-${IMAGE_TAG}-${JOBID}
  spec:
    template:
      spec:
        containers:
        - name: notifications-do-nothing
          image: quay.io/app-sre/ubi8-ubi-minimal:latest
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        restartPolicy: Never
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: JOBID
  generate: expression
  from: "[0-9a-f]{7}"
