---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: notifications-do-nothing
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: notifications-backend-${IMAGE_TAG}
    annotations:
      ignore-check.kube-linter.io/unset-cpu-requirements : "Not required for this job that does nothing"  
      ignore-check.kube-linter.io/unset-memory-requirements : "Not required for this job that does nothing"  
  spec:
    envName: ${ENV_NAME}
    appName: notifications-backend
    jobs:
      - do-nothing
parameters:
- name: ENV_NAME
  description: ClowdEnvironment name (ephemeral, stage, prod)
  required: true
- name: IMAGE_TAG
  value: ''
  required: true
