---
apiVersion: v1
kind: Template
metadata:
  name: notifications-do-nothing
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: notifications-do-nothing-job-${IMAGE_TAG}-${JOBID}
  spec:
    containers:
    - name: notifications-do-nothing
      image: redhat/ubi8-micro
      command: ["exit 0"]
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: JOBID
  generate: expression
  from: "[0-9a-f]{7}"
