{
 "title": "Notifications Dashboard",
 "tags": [ "notifications" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": "notifications-gw, notifications-backend"
   },
   {
    "name": "jvmcontainer",
    "query": "notifications-backend, notifications-gw"
   },
   { "name": "kubernetes_namespace", "label": "Kubernetes Namespace", "query": "up" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Notifications Dashboard\nIf you make changes, please make sure you export the dashboard and save the json [in the e2e-deploy repo](https://github.com/RedHatInsights/e2e-deploy/blob/master/templates/mnm/grafana-config/prod/dashboards/Notifications.json).\n\nTo see:\n- Prod metrics, use [the prod Grafana instance](https://metrics.1b13.insights.openshiftapps.com): pick \"Role=mnm\" and \"Kubernetes Namespace=notifications-prod\" above\n- CI metrics, use [the dev Grafana instance](https://metrics-mnm-ci.5a9f.insights-dev.openshiftapps.com) pick \"Role=mnm-ci\" and \"Kubernetes Namespace=notifications-ci\" above\n- QA metrics, use [the dev Grafana instance](https://metrics-mnm-ci.5a9f.insights-dev.openshiftapps.com) pick \"Role=mnm-ci\" and \"Kubernetes Namespace=notifications-qa\" above"
   },
   "content": "# Notifications Dashboard\nIf you make changes, please make sure you export the dashboard and save the json [in the e2e-deploy repo](https://github.com/RedHatInsights/e2e-deploy/blob/master/templates/mnm/grafana-config/prod/dashboards/Notifications.json).\n\nTo see:\n- Prod metrics, use [the prod Grafana instance](https://metrics.1b13.insights.openshiftapps.com): pick \"Role=mnm\" and \"Kubernetes Namespace=notifications-prod\" above\n- CI metrics, use [the dev Grafana instance](https://metrics-mnm-ci.5a9f.insights-dev.openshiftapps.com) pick \"Role=mnm-ci\" and \"Kubernetes Namespace=notifications-ci\" above\n- QA metrics, use [the dev Grafana instance](https://metrics-mnm-ci.5a9f.insights-dev.openshiftapps.com) pick \"Role=mnm-ci\" and \"Kubernetes Namespace=notifications-qa\" above"
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Up/Down \"$service\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "repeat": "service",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "up{container=\"notifications-gw\", endpoint=\"notifications-gw\", service=\"notifications-gw\"}"
    }
   ]
  },
  {
   "title": "Up/Down \"$service\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "up{container=\"notifications-backend\",endpoint=\"notifications-backend\",service=\"notifications-backend\"}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Up/Down \"notifications-backend\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "up{container=\"notifications-backend\", endpoint=\"notifications-backend\", service=\"notifications-backend\"}"
    }
   ]
  },
  {
   "title": "restarts \"notifications-backend\"",
   "type": "singlestat",
   "description": "This shows the number of restarts for the latest pod that's running in that time period",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"notifications-backend\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Up/Down \"$service\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 2 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "up{container=\"notifications-gw\", endpoint=\"notifications-gw\", service=\"notifications-gw\"}"
    }
   ]
  },
  {
   "title": "restarts \"notifications-gw\"",
   "type": "singlestat",
   "description": "This shows the number of restarts for the latest pod that's running in that time period",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"notifications-gw\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "3Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "3scale API error rate",
   "type": "graph",
   "description": "Proportion of 5xx status codes returned from this service.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"notifications\"}[5m]))/sum(rate(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency(3Scale)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"notifications\"}[1m])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Nb restarts \"$service\"",
   "type": "singlestat",
   "description": "This shows the number of restarts for the latest pod that's running in that time period",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nb restarts \"$service\"",
   "type": "singlestat",
   "description": "This shows the number of restarts for the latest pod that's running in that time period",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nb restarts \"$service\"",
   "type": "singlestat",
   "description": "This shows the number of restarts for the latest pod that's running in that time period",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage \"$service\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='notifications-prod',container=\"$service\"}) BY (pod, namespace)"
    }
   ]
  },
  {
   "title": "Memory usage \"$service\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='notifications-prod',container=\"$service\"}) BY (pod, namespace)"
    }
   ]
  },
  {
   "title": "Memory usage \"$service\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='notifications-prod',container=\"$service\"}) BY (pod, namespace)"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Payload processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(application_engine_input_processed_total{namespace=\"$kubernetes_namespace\"}[2m])",
     "legendFormat": "Received (Per second) {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(application_engine_input_processed_errors_total{namespace=\"$kubernetes_namespace\"}[2m])",
     "legendFormat": "Errors (Absolute)  {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "JVM $jvmcontainer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }, "repeat": "jvmcontainer" },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " base_memory_maxHeap_bytes{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "base_memory_usedHeap_bytes{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"} /  base_memory_maxHeap_bytes",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "JVM Base Thread Count (Deamon and non Deamon)"
    }
   ]
  },
  { "title": "JVM $jvmcontainer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " base_memory_maxHeap_bytes{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "base_memory_usedHeap_bytes{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"} /  base_memory_maxHeap_bytes",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{service=\"$jvmcontainer\", namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "JVM Base Thread Count (Deamon and non Deamon)"
    }
   ]
  }
 ]
}