---
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdJobInvocation
metadata:
  name: populate-org-id-column
spec:
  appName: notifications-backend
  jobs:
    - org-id-populator-behavior-group
    - org-id-populator-email-aggregation
    - org-id-populator-endpoints
    - org-id-populator-endpoint-email-subscriptions
    - org-id-populator-event
