---
apiVersion: v1
kind: Template
metadata:
  name: notifications-engine-post-deployment-tests
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: ${NAME_STUB}-${UID}
  spec:
    appName: notifications-backend
    testing:
      iqe:
        debug: false
        env:
          - name: 'ENV_FOR_DYNACONF'
            value: 'stage_post_deploy'
          - name: 'DYNACONF_DEFAULT_USER'
            value: ${DYNACONF_DEFAULT_USER}
          - name: 'IQE_MARKER_EXPRESSION'
            value: 'notif_engine and api'
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique CJI name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
- name: NAME_STUB
  description: "Basename for the automation pods"
  value: "notifications-engine-tests"
- name: DYNACONF_DEFAULT_USER
  description: The user to be impersonated in the tests
  value: "notifications_admin"
