---
apiVersion: v1
kind: Template
metadata:
  name: notifications-drawer-post-deployment-tests
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: notifications-connector-drawer-tests-${UID}
  spec:
    appName: notifications-connector-drawer
    testing:
      iqe:
        debug: false
        dynaconfEnvName: stage_post_deploy
        filter: ''
        marker: 'notif_drawer and api'
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique CJI name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
