notifications.connector.http.client-error.log-level=ERROR
notifications.connector.http.server-error.log-level=ERROR
notifications.connector.name=email_subscription
notifications.connector.supported-connector-headers=${notifications.connector.name}

# SmallRye Reactive Messaging Kafka config
mp.messaging.incoming.incomingmessages.group.id=notifications-connector-email
smallrye.messaging.worker.connector-thread-pool.max-concurrency=20

# High-volume Kafka topic
mp.messaging.incoming.highvolumemessages.topic=platform.notifications.connector.email.high.volume
mp.messaging.incoming.highvolumemessages.group.id=notifications-connector-email
mp.messaging.incoming.highvolumemessages.failure-strategy=ignore

quarkus.http.port=9003

quarkus.log.cloudwatch.enabled=false
quarkus.log.cloudwatch.level=INFO
quarkus.log.cloudwatch.log-stream-name=${HOST_NAME:notifications-connector-email}

quarkus.log.sentry.enabled=false
quarkus.log.sentry.in-app-packages=com.redhat.cloud.notifications

quarkus.kafka.devservices.port=9092

# Bop configuration
quarkus.rest-client.bop.url=https://backoffice-proxy.apps.ext.spoke.preprod.us-west-2.aws.paas.redhat.com
# For some environments, bop uses same certificates as recipients-resolver because they are hosted in the same cluster.
quarkus.rest-client.bop.trust-store=${clowder.endpoints.notifications-recipients-resolver-service.trust-store-path}
quarkus.rest-client.bop.trust-store-password=${clowder.endpoints.notifications-recipients-resolver-service.trust-store-password}
quarkus.rest-client.bop.trust-store-type=${clowder.endpoints.notifications-recipients-resolver-service.trust-store-type}
notifications.connector.user-provider.bop.api_token=changeme
notifications.connector.user-provider.bop.client_id=changeme
notifications.connector.user-provider.bop.env=changeme

# The URL for the recipients-resolver using rest client integration
quarkus.rest-client.recipients-resolver.url=${clowder.endpoints.notifications-recipients-resolver-service.url:http://localhost:9008}
quarkus.rest-client.recipients-resolver.trust-store=${clowder.endpoints.notifications-recipients-resolver-service.trust-store-path}
quarkus.rest-client.recipients-resolver.trust-store-password=${clowder.endpoints.notifications-recipients-resolver-service.trust-store-password}
quarkus.rest-client.recipients-resolver.trust-store-type=${clowder.endpoints.notifications-recipients-resolver-service.trust-store-type}

quarkus.unleash.active=false
quarkus.unleash.url=http://localhost:4242

# The engine's hostname in order to be able to fetch the event's payloads from it.
quarkus.rest-client.engine.url=${clowder.endpoints.notifications-engine-service.url:http://localhost:8087}
