apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/notifications-backend?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "master"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/v1.9.0/pipelines/docker-build.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: notifications
    appstudio.openshift.io/component: notifications-connector-splunk
    pipelines.appstudio.openshift.io/type: build
  name: notifications-connector-splunk-on-push
  namespace: hcc-integrations-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/hcc-integrations-tenant/notifications/notifications-connector-splunk:{{revision}}
  - name: dockerfile
    value: ./docker/Dockerfile.notifications-connector-splunk.jvm
  - name: path-context
    value: .
  pipelineRef:
    name: docker-build
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
