parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es6: true
settings:
  react:
    version: '17.0'
plugins:
  - react-hooks
  - simple-import-sort
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 7
  sourceType: module
globals:
  beforeAll: true
  describe: true
  expect: true
  global: true
  insights: true
  it: true
  mount: true
  process: true
  render: true
  shallow: true
  React: true
rules: # Todo: Remove javascript rules that are duplicated on typescript
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/explicit-module-boundary-types':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      ignoreRestSiblings: true
  '@typescript-eslint/naming-convention':
    - error
    - selector: default
      format:
        - camelCase
        - PascalCase
        - snake_case
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: allow
    - selector: variable
      format:
        - PascalCase
        - camelCase
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: allow
    - selector: typeLike
      format:
        - PascalCase
        - UPPER_CASE
    - selector: property
      modifiers:
        - readonly
      format:
        - UPPER_CASE
        - camelCase
      leadingUnderscore: allow
      trailingUnderscore: allow
  array-bracket-spacing:
    - error
    - always
    - objectsInArrays: false
  comma-dangle: 2
  comma-spacing:
    - 2
    - after: true
  comma-style: 2
  curly:
    - error
    - all
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  func-names:
    - error
    - never
  indent:
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: 0
      ImportDeclaration: 1
      ObjectExpression: 1
  react/jsx-curly-spacing:
    - error
    - always
    - allowMultiline: false
    - spacing:
        - objectLiterals:
            - never
  react/prop-types: off
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: always
      afterOpening: never
      beforeClosing: allow
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style:
    - error
    - unix
  max-len:
    - 2
    - 150
  new-cap: 2
  no-bitwise: 2
  no-caller: 2
  no-console: off
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces: 2
  no-undef: 2
  no-var: 2
  no-with: 2
  object-shorthand: 2
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
      arraysInObjects: false
  one-var:
    - error
    - never
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: block-like
      next: '*'
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-extra-semi:
    - error
  space-before-blocks: 2
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops:
    - error
    - words: false
      nonwords: false
  vars-on-top: 2
  wrap-iife: 2
  yoda:
    - error
    - never
