{
 "title": "Notifications Dashboard",
 "tags": [ "notifications" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "environment",
    "query": "crcs02ue1-prometheus, crcp01ue1-prometheus"
   }
  ]
 },
 "panels": [
  { "title": "SLO/SLI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO for Error [30d]",
   "type": "gauge",
   "description": "Visualization of SLO movement",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:status_5xx:pctl5rate5m{exported_service=\"notifications\"}[30d])",
     "legendFormat": "SLO at time [30d]"
    }
   ]
  },
  {
   "title": "SLO for latency [30d]",
   "type": "gauge",
   "description": "Visualization of SLO movement",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"notifications\"}[30d])",
     "legendFormat": "SLO at time [30d]"
    }
   ]
  },
  {
   "title": "Notifications Backend - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-backend-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Notifications Backend - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-backend-service\"})"
    }
   ]
  },
  {
   "title": "Notifications Engine - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-engine-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Notifications Engine - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-engine-service\"})"
    }
   ]
  },
  {
   "title": "Notifications GW - UPs",
   "type": "stat",
   "description": "Number of pods currently UP",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-gw-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Notifications GW - Restarts",
   "type": "stat",
   "description": "Number of current restarts (since pod deployment)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-gw-service\"})"
    }
   ]
  },
  { "title": "External dependencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "RBAC - Maximum time spent by account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rbac_get_users_total_seconds_max{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(rbac_get_users_page_seconds_count{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "page"
    }
   ]
  },
  {
   "title": "RBAC -Users per account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rbac_users{job=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "RBAC - Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rbac_failures_total[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Events consumption per application",
   "type": "graph",
   "description": "In events per min",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(input_consumed_seconds_count{service=\"notifications-engine-service\"}[5m])) by (application,bundle)",
     "legendFormat": "{{bundle}}/{{application}}"
    }
   ]
  },
  {
   "title": "Payload processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(processor_input_processed_total{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "processed (per minute) {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(increase(input_rejected_total{service=\"notifications-engine-service\"}[5m]))",
     "legendFormat": "rejected (per minute) {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processed email notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(processor_email_processed_total[5m])) by (application,bundle)",
     "legendFormat": "{{bundle}}/{{application}}"
    }
   ]
  },
  {
   "title": "Processed webhook notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(processor_webhook_processed_total[5m]))",
     "legendFormat": "webhooks"
    }
   ]
  },
  {
   "title": "Aggregator cronjob - duration in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(aggregator_job_duration_seconds[5m])",
     "legendFormat": "aggregator cron job"
    }
   ]
  },
  {
   "title": "Aggregator cronjob - last successful run",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregator_job_last_success * 1000"
    }
   ]
  },
  { "title": "Service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "HTTP requests per minute (Backend)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"notifications-backend-service\"}[5m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP requests per minute (Engine)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"notifications-engine-service\"}[5m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP requests per minute (GW)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"notifications-gw-service\"}[5m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Notifications Backend UP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-backend-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Notifications backend restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-backend-service\"})"
    }
   ]
  },
  {
   "title": "Notifications Engine UP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-engine-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Notifications Engine restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-engine-service\"})"
    }
   ]
  },
  {
   "title": "Notifications GW UP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(up{container=\"notifications-gw-service\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Notifications gw restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"notifications-gw-service\"})"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/integrations.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/integrations.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/user-config.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/user-config.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/facets.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/facets.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/events.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/events.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "average response time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/eventTypes.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/eventTypes.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/behaviorGroups.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/behaviorGroups.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/bundles.*\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{service=\"notifications-backend-service\", uri=~\"/api/notifications/.*/bundles.*\"}[5m])) by (uri)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "notifications-backend - memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"notifications-backend-service\"}) BY (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "notifications-gw - memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"notifications-gw-service\"}) BY (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "3Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "API error rate",
   "type": "graph",
   "description": "Proportion of 5xx status codes returned from this service.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"notifications\",status=\"5xx\"}[5m])) / sum(rate(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 61 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"notifications\"}[5m])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"notifications\"}[5m]))",
     "legendFormat": "count"
    }
   ]
  }
 ]
}