name: Base image auto update
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'RedHatInsights/notifications-backend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up skopeo
        run: sudo apt-get install -y skopeo
      - name: Check change
        run: skopeo inspect docker://registry.access.redhat.com/ubi9/openjdk-21-runtime:latest | jq .Digest --raw-output > .baseimage
      - name: Do change if the digest changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'notifications-team@redhat.com'
          git add -A
          git commit -m "Update ubi9/openjdk-21-runtime:latest image digest" || echo "No changes to commit"
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          title: 'Update ubi9/openjdk-21-runtime:latest image digest'
